appname: ''
awsid: ''
awsprofile: ''
awsregion: us-east-1
awssecret: ''
costcenter: ''
datapath: /tmp/instance_data.yml
emailexceptions: false
emailexceptionsrecipient: ''
emailexceptionssender: ScriptException@locahost
emailrecipients: ''
emailsmtpserver: localhost
emailsmtpserverport: 2525
emailstatussender: AWS-Aware Bot (Prod)
emailstatussenderaddress: Aws-aware-bot@localhost
emailtemplatepath: config/templates
environment: ''
logfile: runtime.log
logformat: '%(relativeCreated)6d %(threadName)s %(message)s'
loggingenabled: false
loglevel: INFO
logpath: logs/
monitorconfig: .config/default-monitors.yml
slack_notifications: false
slack_webhooks: ''
suppressconsoleoutput: false
