appname: ''
awsid: ''
awsprofile: default
awsregion: us-east-1
awssecret: ''
costcenter: ''
datapath: /tmp/instance_data.yml
emailexceptions: false
emailexceptionsrecipient: ''
emailexceptionssender: ScriptException@locahost
emailrecipients: consultant@mycompany.com
emailsmtpserver: localhost
emailsmtpserverport: 25
emailstatussender: AWS-Aware Bot
emailstatussenderaddress: Aws-aware-bot@localhost
emailtemplatepath: config/templates
environment: 'prod'
logfile: runtime.log
logformat: '%(relativeCreated)6d %(threadName)s %(message)s'
loggingenabled: false
loglevel: INFO
logpath: logs/
slack_notifications: false
slack_webhooks: []
suppressconsoleoutput: false
