awsid: ''
awsprofile: ''
awsregion: us-east-1
awssecret: ''
datapath: instance_data.yml
emailexceptions: false
emailexceptionsrecipient: ''
emailexceptionssender: ScriptException@locahost
emailrecipients: ''
emailsmtpserver: localhost
emailsmtpserverport: 25
emailstatussender: AWS-Aware Bot
emailstatussenderaddress: Aws-aware-bot@localhost
emailtemplatepath: config/templates
logfile: runtime.log
logformat: '%(relativeCreated)6d %(threadName)s %(message)s'
loggingenabled: false
loglevel: INFO
logpath: logs/
slack_notifications: false
slack_webhooks: []
suppressconsoleoutput: false
